import { PrismaClient } from '@prisma/client';

const p = new PrismaClient();

// ── Dados brutos (tab-separated: NOME \t UNIDADE \t FORNECEDOR) ─────
const RAW = `ABRE TRINCAS (ELLUS)	UNIDADE	MERCANTIL
AÇÚCAR	PEÇA	SUPERMERCADO
ÁGUA SANITÁRIA	PEÇA	SUPERMERCADO
ÁLCOOL	PEÇA	SUPERMERCADO
ALSAN	BALDE	
APLICADOR DE MASSA (CELULOIDE)	PEÇA	MERCANTIL
ARAME RECOZIDO Nº 12 KG	KG	CASA DUARTE
ARAME RECOZIDO Nº 14 KG	PEÇA	MERCANTIL
ARAME RECOZIDO Nº 18 KG	PEÇA	CASA DUARTE
AREIA (FINA)	LATA	
AREIA (GROSSA)	LATA	
ARGAMASSA ACIII	PACOTE	
AXTON MANTA LIQUIDA	BALDE	AXTON
AZULLIM TIRA LIMO	PEÇA	MERCANTIL
BALDE (REUSO - RECIPIENTE DE PRODUTOS)	UNIDADE	
BALDE (REUSO - RECIPIENTE DE PRODUTOS)	Unidade	
BANDEJA PARA PINTURA	Unidade	
BIANCO VEDACIT (ADESIVO DE ALTO DESEMPENHO)	BALDE	
BLOCO DE ESPUMA	PEÇA	CASA SÃO JULIÃO
BROCA 10" (MADEIRA)	UNIDADE	
BROCA 10" (METAL)	UNIDADE	
BROCA 10" (VÍDIA/CONCRETO)	UNIDADE	
BROCA 12" (MADEIRA)	UNIDADE	
BROCA 12" (METAL)	UNIDADE	
BROCA 12" (VÍDIA/CONCRETO)	UNIDADE	
BROCA 6" (MADEIRA)	UNIDADE	
BROCA 6" (METAL)	UNIDADE	
BROCA 6" (VÍDIA/CONCRETO)	UNIDADE	
BROCA 8" (MADEIRA)	UNIDADE	
BROCA 8" (METAL)	UNIDADE	
BROCA 8" (VÍDIA/CONCRETO)	UNIDADE	
ESCOVA RETANGULAR (TIGRE)	UNIDADE	MERCANTIL
BROCHA RETANGULAR MADEIRA (MAX)	UNIDADE	MERCANTIL
CABO DE VASSOURA	UNIDADE	
CABO PARA MARRETA	PEÇA	MERCANTIL
CABO PARA ROLO 23"	PEÇA	MERCANTIL
CADEADO	KG	MERCANTIL
CAFÉ	PEÇA	SUPERMERCADO
CAIXA DE BOMBOM	PEÇA	SUPERMERCADO
CAMISA DRENANTE	METRO LINEAR	CENTERGEO
CARTUCHO DE GÁS	KG	MERCANTIL
CIMENTO	SACO	
COLA	Unidade	
COLHERZINHA DE CAFÉ	PEÇA	SUPERMERCADO
CONE DE PLÁSTICO	PEÇA	
CONE DE PLÁSTICO	PEÇA	
CONE DE PLÁSTICO (TIPO POSTE)	PEÇA	
CONTRA UMIDADE (SIMILAR IMPER1)	BALDE 18 L	VIAPOL
COPO DESCARTÁVEL (ÁGUA)	PEÇA	SUPERMERCADO
COPO DESCARTÁVEL (CAFÉ)	PEÇA	SUPERMERCADO
CORRENTE DE AÇO	PEÇA	MERCANTIL
CORRENTE DE PLÁSTICO (SEGURANÇA)	SACO	
DENVER ANTIMOFO (12K)	BALDE	DENVER
DENVER ANTIMOFO (4K)	GALÃO 4 KG	DENVER
DENVER BLITZ (18 KG)	BALDE	DENVER
DENVER CAL (1L)	FRASCO	DENVER
DENVER CAL (3,6)	GALÃO 3,6 L	DENVER
DENVER CAL (ADESIVO PLASTIF. P/ ARGAMASSA - 18 LTS)	BALDE	DENVER
DENVER CAL (ADESIVO PLASTIF. P/ ARGAMASSA - 200 LTS)	TAMBOR	DENVER
DENVER CAL (ADESIVO PLASTIF. P/ ARGAMASSA)	BALDE	
DENVER CAMADA SEPARADORA	M²	DENVER
DENVER CRIL PAREDE (18 KG)	BALDE	DENVER
DENVER CRIL PAREDE (3,6 KG)	GALÃO	DENVER
DENVER CRIL SUPER BRANCO (12 KG)	BALDE	DENVER
DENVER CRIL SUPER BRANCO (4 KG)	GALÃO 4 KG	DENVER
DENVER CRIL SUPER CINZA (12 KG)	BALDE	DENVER
DENVER CRIL SUPER CINZA (4 KG)	GALÃO 4 KG	DENVER
DENVER DESFORMA	TAMBOR	DENVER
DENVER DESFORMA (18L)	BALDE	DENVER
DENVER DESFORMA (3,6L)	GALÃO 3,6 L	DENVER
DENVER DESMOLDANTE (18 LT)	BALDE	DENVER
DENVER DESMOLDANTE (3,6 L)	GALÃO 3,6 L	DENVER
DENVER FIX CHAPISCO	1 L	DENVER
DENVER FIX CHAPISCO (GL 3,60)	GALÃO 3,6 L	DENVER
DENVER FIX CHAPISCO BD	BALDE	DENVER
DENVER FIX CHAPISCO TBR	TAMBOR	DENVER
DENVER GROUT	SACO	DENVER
DENVER GROUT (GRAUTE À BASE DE CIMENTO P/ USO GERAL)	BALDE	
DENVER GROUT (GRAUTE À BASE DE CIMENTO P/ USO GERAL)	BALDE	
DENVER IMPER 1 (ADITIVO IMPERM. P/ ARGAMASSA E CONCRETO)	BALDE	
DENVER IMPER 1 (ADITIVO IMPERM. P/ ARGAMASSA E CONCRETO)	BALDE	
DENVER IMPER 1 BD	BALDE	DENVER
DENVER IMPER 1 GL 3,6	GALÃO 3,6 L	DENVER
DENVER IMPER 1 TBR	TAMBOR	DENVER
DENVER IMPER BLACK 18L	LATA	DENVER
DENVER IMPER BLACK 3,6 LT	GALÃO 3,6 L	DENVER
DENVER IMPER BLACK 900 ML	LATA 0,9L	DENVER
DENVER IMPERBLACK (PINT. ASFÁLT. PROT. E IMPERM.)	BALDE	
DENVER IMPERBLACK (PINT. ASFÁLT. PROT. E IMPERM.)	BALDE	
DENVER IMPERBLACK TBR	TAMBOR	DENVER
DENVER LAJE PRETO 3,6 LT	GALÃO 3,6 L	DENVER
DENVER LAJE PRETO BD	BALDE	DENVER
DENVER MANTA PRIMER ACQUA (PRIMER BASE ÁGUA P/ MANTA ASFÁLT. 18L)	BALDE 18L	
DENVER MANTA PRIMER ACQUA (PRIMER BASE ÁGUA P/ MANTA ASFÁLT. 3,6L)	BALDE 3,6L	
DENVER NIZ ACQUA 18LTS	BALDE	DENVER
DENVER POLIASFALTO 5K	BARRA	DENVER
DENVER POXI MAX (ADESIVO ESTRUTURAL BASE EPÓXI DE CONSIST. PASTOSA - CONJ. A+B)	BALDE	
DENVER POXI MAX (ADESIVO ESTRUTURAL BASE EPÓXI DE CONSIST. PASTOSA - CONJ. A+B)	BALDE	
DENVER PREN PU (COMPONENTE A)	BALDE	
DENVER PREN PU (COMPONENTE A)	BALDE	
DENVER REPARO 12K	GALÃO 4 KG	
DENVER REPELE ACQUA (SILICONE INCOLOR REPELENTE DE ÁGUA)	BALDE	
DENVER REPELE ACQUA (SILICONE INCOLOR REPELENTE DE ÁGUA)	BALDE	
DENVER REPELE ACQUA 18L	BALDE	DENVER
DENVER SOPREMA (MAX ANTIRRAIZ)	BALDE	
DENVER SOPREMA (MAX ANTIRRAIZ)	BALDE	
DENVER TEC	BALDE	
DENVER TEC 100 18 KG	CAIXA 18 KG	DENVER
DENVER TEC 540 18 KG	CAIXA 18 KG	DENVER
DENVER TERM E OS 25MM	PLACA	DENVER
DENVER TINTA MAS ANTRAIZ	18L	DENVER
DENVERBLITZ	BALDE	
DENVERBLITZ	BALDE	
DENVERCRIL PAREDE	BALDE	
DENVERCRIL PAREDE	BALDE	
DENVERFITA 05CM X 10M	ROLO	DENVER
DENVERFITA 10 CM X 10 M	ROLO	DENVER
DENVERFITA 10CM X 1M	ROLO	DENVER
DENVERFITA 15CMX10M	ROLO	DENVER
DENVERFITA 20CM X 10M	METRO	DENVER
DENVERFITA 30 CM	METRO	DENVER
DENVERFITA 45CM X 10M	M²	DENVER
DENVERFITA 90CM X 10M	METRO	DENVER
DENVERFITA 98CM X 10M	METRO	DENVER
DENVERFIX ACRILICO 18LT	BALDE	DENVER
DENVERFIX CHAPISCO (ADESIVO PARA CHAPISCOS E ARGAMASSAS)	BALDE	
DENVERFIX CHAPISCO (ADESIVO PARA CHAPISCOS E ARGAMASSAS)	BALDE	
DENVERFRIO ASFALTO	BALDE	DENVER
DENVERGROUT EPOXI	CONJUNTO	DENVER
DENVERHIDRORREPELENTE ACQUA	GALÃO 3,6 L	DENVER
DENVERMANTA LAJE 30KG	M²	DENVER
DENVERNIZ ANTIPICHAÇÃO	GALÃO 3,6 L	DENVER
DENVERNIZ SB	18 L	DENVER
DENVERPOXI	CONJUNTO	DENVER
DENVERPOXI MAX	CONJUNTO	DENVER
DENVERPREN 16 KG	LATA	DENVER
DENVERPREN PU	CONJUNTO 18KG	DENVER
DENVERPRIMER MAX LT18L	LATA	DENVER
DENVERSOL TOP REFLECTIVE	BALDE	DENVER
DENVERSOLVENTE 300	5 L	DENVER
DENVERTEC 700	CAIXA	
DENVERTEC 700	CAIXA	
DENVERTEC 700 18 KG	CAIXA 18 KG	DENVER
DENVERTEC ELASTIC FIBRAS	CAIXA	DENVER
DENVERTEC ELASTIC HP	CAIXA	DENVER
DESINFETANTE	GALÃO	MERCANTIL
DESINGRIPANTE	PEÇA	MERCANTIL
DETERGENTE	PEÇA	SUPERMERCADO
DF 8 BRANCO 12KG	BALDE	MC - BALCHEMIE
DILUENTE PREMIUM	LATA	
DISCO DE CORTE INOX 4"	PEÇA	MERCANTIL
DISCO DE CORTE INOX 7"	PEÇA	MERCANTIL
DISCO DE DESBASTE 4"	PEÇA	MERCANTIL
DISCO DE DESBASTE 7"	PEÇA	MERCANTIL
DISCO DE POLIMENTO 4"	PEÇA	MERCANTIL
DISCO DE POLIMENTO 4" LIXA 24	PEÇA	MERCANTIL
DISCO DE SERRA (MADEIRA)	PEÇA	MERCANTIL
DISCO DIAMANTADO SEGMENTADO 4"	PEÇA	MERCANTIL
DISCO DIAMANTADO SEGMENTADO 7"	PEÇA	MERCANTIL
DISCO DIAMANTADO TURBO 4"	PEÇA	MERCANTIL
DISCO REBOLO DIAMANTADO SEGMENTADO	PEÇA	MERCANTIL
EMCEKRETE 50- 25KG	CS	MC- BALCHEMIE
ENFORCA GATO 3,5 X 150 (PC C/ 100)	PEÇA	MERCANTIL
ENFORCA GATO 3,6 X 200 (PC C/ 100)	PEÇA	MERCANTIL
ENFORCA GATO AMARELO 2,5 X 100 (50 UNI)	PEÇA	MERCANTIL
ENFORCA GATO AZUL 2,5 X 100 (50 UNI)	PEÇA	MERCANTIL
ENFORCA GATO VERDE 2,5 X 100 (50 UNI)	PEÇA	MERCANTIL
ENFORCA GATO VERMELHO 2,5 X 100 (50 UNI)	PEÇA	MERCANTIL
ENGATE RÁPIDO COM EMENDA	PEÇA	CASA DUARTE
EPÓXI BASE ÁGUA	BALDE	
ESCOVA DE AÇO	PEÇA	MERCANTIL
ESCOVA DE AÇO - MAKITA	PEÇA	MERCANTIL
ESCOVA DE AÇO TRAMONTINA	UNIDADE	MERCANTIL
ESMALTE (TINTA)	LATA	
ESMALTE PU PISCINAS (KIT PARA PINTURA)	BALDE	
ESPONJA/BUCHA	PEÇA	SUPERMERCADO
ESPUMA ESPANSIVA (SOLUFIX)	UNIDADE	SACHI
ESPUMA EXPANSIVA	KG	MERCANTIL
ESTOPA	PEÇA	SUPERMERCADO
EXTENSOR PARA ROLO	PEÇA	
FERTILIZANTE (FORTH JARDIM)	BALDE	
FILTRO DE CAFÉ 103	PEÇA	SUPERMERCADO
FITA CREPE 18MM	PEÇA	MERCANTIL
FITA CREPE 24MM	PEÇA	MERCANTIL
FITA CREPE 48MM	PEÇA	MERCANTIL
FITA ISOLANTE	PEÇA	MERCANTIL
FITA VEDA ROSCA	PEÇA	MERCANTIL
FITA ZEBRADA	PEÇA	MERCANTIL
FOLHA DE LIXA D'ÁGUA FINA	PEÇA	MERCANTIL
FOLHA DE LIXA DE D'AGUA GROSSA	PEÇA	MERCANTIL
FOLHA DE LIXA DE D'ÁGUA MÉDIA	PEÇA	MERCANTIL
FOLHA DE LIXA DE FERRO FINA	PEÇA	MERCANTIL
FOLHA DE LIXA DE FERRO GROSSA	PEÇA	MERCANTIL
FOLHA DE LIXA DE FERRO MÉDIA (80)	PEÇA	MERCANTIL
FOLHA DE LIXA DE PAREDE FINA (100/120)	PEÇA	MERCANTIL
FOLHA DE LIXA DE PAREDE GROSSA (50/50/60)	PEÇA	MERCANTIL
FOLHA DE LIXA DE PAREDE MÉDIA	PEÇA	MERCANTIL
FOSFATOL (CONVERTOR DE FERRUGEM)	BALDE	
FUNDO PREPARADOR PARA PAREDES (BASE ÁGUA)	BALDE	
GARFO PARA ROLO ATLAS	UNIDADE	MERCANTIL
GARRAFA DE CAFÉ	PEÇA	SUPERMERCADO
GRAMPO 26/6 C/5000	PEÇA	PAPELARIA REAL
GUARDANAPO ROLO	PEÇA	SUPERMERCADO
HP ELASTIC	CAIXA	
HYDRO 100 18 KG	SACO	MC - BALCHEMIE
HYDRO 500 18,2 KG	CAIXA	MC - BALCHEMIE
IMPER MANTA 3MM MAX ANTIRRAIZ (MANTA ANTIRRAIZ)	METRO	DENVER
IMPER MANTA COR 3 MM (MANTA COR 3)	M²	DENVER
IMPER MANTA COR 4MM PP (MANTA COR 4)	M²	DENVER
IMPER MANTA LAJE PP 3MM (MANTA ASFÁLTICA 3)	M²	DENVER
IMPER MANTA LAJE PP 4MM (MANTA ASFÁLTICA 4)	M²	DENVER
IMPER MANTA PRIMER (3,6 L)	GALÃO 3,6 L	DENVER
IMPER MANTA TELHADO AL 3MM (MANTA ALUMÍNIO 3)	M²	DENVER
IMPER MANTA TELHADO AL 3MM (MANTA ALUMÍNIO)	M²	DENVER
IMPER MANTA TELHADO AL 4MM (MANTA ALUMÍNIO 4)	M²	DENVER
JUNTA DE PISO 1,5 MM (100UNI)	PEÇA	MERCANTIL
LÂMINAS DE ESTILETE	PEÇA	MERCANTIL
LAMPADA	PEÇA	MERCANTIL
LÁPIS DE PEDREIRO	PEÇA	CASA DUARTE
LIMPA PEDRAS	GALÃO	
LINHA DE PEDREIRO	PEÇA	MERCANTIL
LINHA DE PESCA 0,5	PEÇA	MERCANTIL
LIXA 4" FINA	PEÇA	MERCANTIL
LIXA 4" GROSSA	PEÇA	MERCANTIL
LIXA 7" FINA	PEÇA	MERCANTIL
LIXA 7" GROSSA	PEÇA	MERCANTIL
LIXA 7" MÉDIA	PEÇA	MERCANTIL
LIXA DE METRO GROSSA	PEÇA	CASA SÃO JULIÃO
LIXA DE METRO GROSSA	PEÇA	CASA SÃO JULIÃO
LONA	METRO	UNIÃO AGROPECUARIA
LONA AZUL	UNIDADE	MERCANTIL
LONA PRETA 4 X 100	METRO	MERCANTIL
MANGUEIRA (CORRUGADA PARA BOMBA D'ÁGUA - 5")	Metro	
MANTA (FITA 10 CM)	METRO	
MANTA (FITA 15 CM)	METRO	
MANTA (FITA 20 CM)	METRO	
MANTA (FITA 30 CM)	METRO	
MANTA (FITA 45 CM)	METRO	
MANTA (FITA 5 CM)	METRO	
MANTA (FITA 60 CM)	METRO	
MANTA (FITA 90 CM)	METRO	
MANTA (FITA 98 CM)	METRO	
MANTA DE DRENO (CENTERGEL - TIPO 2L 1L)	M²	CENTERGEL
MANTA DE DRENO (MCDRAIN FP)	M²	MACCAFERRY
MANTA DRENO (GEOCOMPOSTO LGT)	M²	CENTERGEO
MANTA GEOTEXTIL (200GR/2,30M)	METRO LINEAR	CENTERGEO
MANTA LIQUIDA (15K AXTON)	BALDE	AXTON
MANTA LÍQUIDA ACRÍLICA PREMIUM (VEDALAGE PLUS)	BALDE	
MANTA LIQUIDA ALSAN ACRIL (12K)	BALDE	SOPREMA
MANTEIGA	PEÇA	IRMÃO ALMEIDA
MARGARINA	PEÇA	SUPERMERCADO
MASSA ACRÍLICA	Galão	
MASSA ASFÁLTICA (GRANDE - BETUME)	BARRA	
MASSA ASFÁLTICA (GRANDE)	BARRA	
MASSA ASFÁLTICA (PEQUENA - BETUME)	BARRA	
MASSA ASFÁLTICA (PEQUENA)	BARRA	
MASSA CORRIDA (BALDE)	BALDE	
MASSA CORRIDA (LATA)	LATA	
MC- EMCEKRETE -25 KG	SACO	MC - BALCHEMIE
MC- FAST BLOCK 13KG	CAIXA	MC - BALCHEMIE
MC PROFT 900 EL (MEMB. ELÁST. IMPERM. C/ FIBRA)	CAIXA	
MC PROFT 900 EL (MEMB. ELÁST. IMPERM. C/ FIBRA)	CAIXA	
MC- PROOF 900 EL	CAIXA	MC- BALCHEMIE
MC -PROOF MULT (18KG)	BALDE	MC - BALCHEMIE
MC-DUR 1300 (1KG)	CONJUNTO	MC - BALCHEMIE
MC-DUR TX 1300 (1KG)	CONJUNTO	MC - BALCHEMIE
MC-FLEX 450 VE (6,6L)	LITRO	MC-BALCHEMIE
MC-FLEX PU 40 CINZA (800G)	SACHE	MC- BALCHEMIE
MC-XYPEX CONCEBTRADO (25 KG)	SACO	MC - BALCHEMIE
MC-XYPEX MODIFICADO	SACO	MC - BALCHEMIE
MC-XYPEX PATCHN PLUG	SACO	MC- BALCHEMIE
MEMBRANA DE POLIURETANO (POXPUR - IMPERMEABILIZANTE)	BALDE	
NAFTALINA	PEÇA	SUPERMERCADO
PALHA DE AÇO	PEÇA	SUPERMERCADO
PANO	PEÇA	SUPERMERCADO
PAPEL HIGIÊNICO	PEÇA	SUPERMERCADO
PELÍCULA ESMA (TINTA)	LATA	
PERFEX	PEÇA	SUPERMERCADO
PINCEL 1"	PEÇA	MERCANTIL
PINCEL 2"	PEÇA	MERCANTIL
PINCEL 3"	PEÇA	MERCANTIL
PLUGUE - TIPO "T" PARA TOMADAS	Unidade	
PLUGUE/PINO - TIPO "T" PARA TOMADAS	UNIDADE	
PLUGUE/PINO (FÊMEA 20A)	PEÇA	MERCANTIL
PLUGUE/PINO (MACHO 10A)	PEÇA	MERCANTIL
PÓ 2	CAIXA 15KG	VIAPOL
POLIASFATO	BARRA	DENVER
POX PUR (PU250 - 1,76 KG)	BALDINHO	
POX PUR (PU250) - 1,76 KG	BALDINHO	
POXPUR MAXX CONST MEM POLIURETANO (12)	BALDE 12K	MACFEX
POXPUR MAXX CONST MEM POLIURETANO (4,5)	BALDE 4,5	DISTRIMAC
POXPUR PU 200 BO-COMPONENTE (3,5)	CONJUNTO 3,5	DISTRIMAC
POXPUR PU 250 BO-COMPONENTE (3,6)	CONJUNTO 3,6	DISTRIMAC
PREGO (17X21)	KG	CASA DUARTE
PREGO (18X30)	KG	CASA DUARTE
PROOF 500	CAIXA	
PROOF 500	CX	
PU 40 - (COR: BEGE)	BISNAGA	
PU 40 - (COR: BRANCA)	BISNAGA	
PU 40 - (COR: CINZA)	BISNAGA	
PU 40 - (COR: PRETA)	BISNAGA	
PU 40 - (MACFLEX – COR: BEGE)	BISNAGA	DISTRIMAC
PU 40 - (MACFLEX – COR: BRANCO)	BISNAGA	DISTRIMAC
PU 40 - (MACFLEX – COR: CINZA)	BISNAGA	DISTRIMAC
PU 40 - (MACFLEX – COR: PRETO)	BISNAGA	DISTRIMAC
PU200 (PROXPUR - IMPERMEABILIZANTE)	BALDE	
RECUBRIPLAST PISCINA (TINTA ACRÍLICA IMPERMEÁVEL)	BALDE	
REJUNTE ESPECIAL ACRÍLICO (PORTO KOLL PREMIUM)	BALDE	
REMOVEDOR PASTOSO	LATA	
REQUISIÇÃO C/CÓPIA	PEÇA	PAPELARIA REAL
RESINA ACRÍLICA (TINTA)	LATA	
RODO (NOVO)	PEÇA	
RODO (USADO)	PEÇA	
ROLO DE ESPUMA (COMPEL - TAM: 15 CM)	UNIDADE	MERCANTIL
ROLO DE ESPUMA (COMPEL - TAM: 5 CM)	UNIDADE	MERCANTIL
ROLO DE ESPUMA (TAM: 05CM)	PEÇA	MERCANTIL
ROLO DE ESPUMA (TAM: 15CM)	PEÇA	MERCANTIL
ROLO DE ESPUMA (TAM: 23 CM)	UNIDADE	MERCANTIL
ROLO DE ESPUMA (TAM: 9CM)	UNIDADE	MERCANTIL
ROLO DE LÃ (COMPEL - TAM: 5 CM)	UNIDADE	MERCANTIL
ROLO DE LÃ (TAM: 15CM)	ROLO	MERCANTIL
ROLO DE LÃ (TIGRE – TAM: 23 CM)	UNIDADE	MERCANTIL
ROLO DE LÃ (TIGRE – TAM: 23CM - FELPUDO)	PEÇA	CASA SÃO JULIÃO
ROLO DE LÃ RESPINGO ZERO (TAM: 05CM)	PEÇA	MERCANTIL
ROLO DE LÃ RESPINGO ZERO (TAM: 09CM)	PEÇA	MERCANTIL
ROLO DE LÃ RESPINGO ZERO (TAM: 15CM)	PEÇA	MERCANTIL
ROLO DE LÃ RESPINGO ZERO (TAM: 23 CM)	UNIDADE	MERCANTIL
ROLO DE LÃ SINT. (COMPEL – TAM: 23CM)	UNIDADE	MERCANTIL
ROLO DE LÃ SINT. (COMPEL – TAM: 9CM)	UNIDADE	MERCANTIL
ROLO DE LÃ SINTÉTICA (TAM: 05CM)	PEÇA	MERCANTIL
ROLO DE LÃ SINTÉTICA (TAM: 09CM)	PEÇA	MERCANTIL
ROLO DE LÃ SINTÉTICA (TAM: 15CM)	PEÇA	MERCANTIL
ROLO DE LÃ SINTÉTICA (TAM: 23CM)	PEÇA	MERCANTIL
ROLO EPOXI (TAM: 23CM)	PEÇA	MERCANTIL
ROLO LÃ S/ RESP. (TAM: 23 CM - STANADRO 1374 – TIGRE)	ROLO	MERCANTIL
SABONETE LÍQUIDO	PEÇA	SUPERMERCADO
SACO DE LIXO (CAPAC: 100 LITROS)	PEÇA	SUPERMERCADO
SACO DE LIXO (CAPAC: 200 LITROS - REFORÇADO)	PEÇA	CASA DAS EMBALAGENS
SACO DE LIXO (CAPAC: 50 LITROS)	PEÇA	SUPERMERCADO
SACO REFORÇADO DE RAÇÃO	PEÇA	UNIÃO AGROPECUARIA
SAPÓLIO	PEÇA	IRMÃO ALMEIDA
SERRINHA	PEÇA	MERCANTIL
S-FLEX PU 35 (COR: BRANCO)	UNIDADE	SACHI
S-FLEX PU 35 (COR: CINZA)	UNIDADE	SACHI
S-FLEX PU 35 (COR: PRETO)	UNIDADE	SACHI
SHERWIN WILLIAMS	BALDE	
SHERWIN WILLIAMS	BALDE	
SIKAFILL RÁPIDO MANTA LIQ (CINZA – 15L)	BALDE	SIKA
SIKAFILL RÁPIDO MANTA LIQ (CINZA – 3,6L)	GALÃO	SIKA
SOLUFIX (CINZA - 800G)	SACHE	SACHI
STAIN PROTETOR MADEIRA (SPARLACK CETOL)	LATA	
TEC100	CAIXA	
TEC540	CAIXA	
TELA (PROTEÇÃO PREDIAL)	METRO	MERCANTIL
TELA POLIÉSTER (PROPORÇ: 1X1 – ROLO: 50 M)	M²	ERNETEX
TELA POLIÉSTER (PROPORÇ: 2X2)	M²	ERNETEX
TEXTURA	SACO	
THINNER	PEÇA	
TINGIDOR	LATA	
TOMADA	PEÇA	
TOP 700 FIBRAS (18K AXTON)	CAIXA	AXTON
TOQUE FOSCO	LATA	
TRINCHA (ATLAS - 300 – TAM: 1")	UNIDADE	MERCANTIL
TRINCHA (ATLAS - 300 – TAM: 2")	UNIDADE	MERCANTIL
TRINCHA (ATLAS – 300 – TAM: 3")	UNIDADE	MERCANTIL
TUBO (CONDUIT/CORRUGADO PARA BOMBA D'ÁGUA)	METRO	
TUBO (GEODRENO - 2,5”)	METRO	CENTERGEO
TUBO (GEODRENO - 4")	METRO	CENTERGEO
TUBO CONDUIT PARA BOMBA D'ÁGUA	Metro	
SILICONE (FLEX - DOWSIL 791 - BEGE - DOW)	BISNAGA	MERCANTIL
SILICONE (FLEX - DOWSIL 791 - BRANCO - DOW)	BISNAGA	MERCANTIL
SILICONE (FLEX - DOWSIL 791 - CINZA - DOW)	BISNAGA	MERCANTIL
SILICONE (FLEX - DOWSIL 791 - PRETO - DOW)	BISNAGA	MERCANTIL
SELANTE MS 426 (HARD - PISCINA - BEGE)	BISNAGA	
SELANTE MS 426 (HARD - PISCINA - BRANCO)	BISNAGA	
SELANTE MS 426 (HARD - PISCINA - CINZA)	BISNAGA	
SELANTE MS 426 (HARD - PISCINA - PRETO)	BISNAGA	
DESENGRIPANTE	FRASCO	
TINTA	LATA	
TÁBUA	UNIDADE	
MC PROOF DF 8 (Manta acrílica impermeável altamente flexível - 12 Kg)	BALDE	MC - BALCHEMIE
FITA ALUMÍNIO 25MM X 30M	UNIDADE Cadastre estes items em materiais relacionando os fornecedores e unidademedidas, sem reedundência`;

// ── Normalização ──────────────────────────────────────────────────
const UNIT_MAP: Record<string, string> = {
  'CAIXA': 'CX', 'CAIXA 15KG': 'CX', 'CAIXA 18 KG': 'CX',
  'M²': 'M2',
  'Metro': 'METRO', 'METRO LINEAR': 'METRO',
  'Unidade': 'UNIDADE',
  '1 L': 'L', '5 L': 'L', '18 L': 'L',
  'GALÃO 4 KG': 'GALÃO', 'GALÃO 3,6 L': 'GALÃO',
  'BALDE 18 L': 'BALDE', 'BALDE 3,6L': 'BALDE', 'BALDE 12K': 'BALDE', 'BALDE 4,5': 'BALDE',
  'BALDE 18L': 'BALDE', 'BALDE 3,6L': 'BALDE', 'BALDE 12K': 'BALDE', 'BALDE 4,5': 'BALDE',
  'LATA 0,9L': 'LATA',
  'CONJUNTO 3,5': 'CONJUNTO', 'CONJUNTO 3,6': 'CONJUNTO', 'CONJUNTO 18KG': 'CONJUNTO',
  'Galão': 'GALÃO',
  'BALDINHO': 'BALDE',
};

const FORN_MAP: Record<string, string> = {
  'MC - BALCHEMIE': 'Mc - Balchemie',
  'MC- BALCHEMIE': 'Mc - Balchemie',
  'MC-BALCHEMIE': 'Mc - Balchemie',
  'CENTERGEO': 'Centergeo',
  'AXTON': 'Feruni Axton',
  'DENVER': 'Denver',
  'VIAPOL': 'Viapol',
  'MERCANTIL': 'Mercantil',
  'DISTRIMAC': 'Distrimac',
  'MACFEX': 'Macfex',
  'MACCAFERRY': 'Maccaferry',
  'SACHI': 'Sachi',
  'SIKA': 'Sika',
  'SOPREMA': 'Soprema',
  'SUPERMERCADO': 'Supermercado',
  'CASA DUARTE': 'Casa Duarte',
  'CASA SÃO JULIÃO': 'Casa São Julião',
  'PAPELARIA REAL': 'Papelaria Real',
  'IRMÃO ALMEIDA': 'Irmão Almeida',
  'CASA DAS EMBALAGENS': 'Casa das Embalagens',
  'UNIÃO AGROPECUARIA': 'União Agropecuária',
  'ERNETEX': 'Ernetex',
  'CENTERGEL': 'Centergel',
};

function normUnit(raw: string): string {
  const trimmed = raw.trim();
  return UNIT_MAP[trimmed] ?? trimmed.toUpperCase();
}

function normForn(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  return FORN_MAP[trimmed] ?? trimmed;
}

// ── Parse + Dedup ──────────────────────────────────────────────────
type MaterialRow = { nome: string; unidade: string; fornecedor: string | null };

function parse(): MaterialRow[] {
  const seen = new Set<string>();
  const rows: MaterialRow[] = [];

  for (const line of RAW.split('\n')) {
    if (!line.trim()) continue;
    // Last line has appended instruction text — skip if doesn't contain tab
    if (!line.includes('\t')) continue;

    const parts = line.split('\t');
    const nome = (parts[0] ?? '').trim().toUpperCase();
    const rawUnit = (parts[1] ?? '').trim();
    const rawForn = (parts[2] ?? '').trim();

    const unidade = normUnit(rawUnit);
    const fornecedor = normForn(rawForn);

    const key = `${nome}||${unidade}`;
    if (seen.has(key)) continue;
    seen.add(key);

    rows.push({ nome, unidade, fornecedor });
  }
  return rows;
}

// ── Main ──────────────────────────────────────────────────────────
async function main() {
  const rollback = process.argv.includes('--rollback');

  const ROWS = parse();

  if (rollback) {
    console.log('Rollback: removendo materiais criados pelo seed-materiais...');
    // Materiais sem código EPI- nem PAT- são os nossos
    const del = await p.material.deleteMany({
      where: { nome: { in: ROWS.map(r => r.nome) } },
    });
    console.log(`Removidos: ${del.count} materiais`);
    return;
  }

  // 1. Unidades de medida
  const allUnits = [...new Set(ROWS.map(r => r.unidade))];
  console.log(`--- Unidades de medida (${allUnits.length}) ---`);
  const umMap: Record<string, number> = {};
  for (const nome of allUnits) {
    const rec = await p.unidadeMedida.upsert({
      where: { nome },
      create: { nome },
      update: {},
    });
    umMap[nome] = rec.id;
    console.log(`  ${rec.nome} (id=${rec.id})`);
  }

  // 2. Fornecedores
  const allForn = [...new Set(ROWS.filter(r => r.fornecedor).map(r => r.fornecedor!))];
  console.log(`\n--- Fornecedores (${allForn.length}) ---`);
  const fornMap: Record<string, number> = {};
  for (const nome of allForn) {
    const existing = await p.fornecedor.findFirst({ where: { nome } });
    if (existing) {
      fornMap[nome] = existing.id;
      console.log(`  ${existing.nome} (id=${existing.id}) [existente]`);
    } else {
      const rec = await p.fornecedor.create({ data: { nome } });
      fornMap[nome] = rec.id;
      console.log(`  ${rec.nome} (id=${rec.id}) [criado]`);
    }
  }

  // 3. Inserir materiais
  console.log(`\n--- Inserindo materiais (${ROWS.length} únicos) ---`);
  let criados = 0;
  let erros = 0;

  for (const r of ROWS) {
    try {
      await p.material.create({
        data: {
          nome: r.nome,
          unidadeId: umMap[r.unidade],
          fornecedorId: r.fornecedor ? (fornMap[r.fornecedor] ?? null) : null,
        },
      });
      criados++;
      const forn = r.fornecedor ? ` [${r.fornecedor}]` : '';
      console.log(`  ${r.nome} | ${r.unidade}${forn}`);
    } catch (e: any) {
      erros++;
      console.log(`  ⚠️  SKIP: ${r.nome} — ${e.message?.slice(0, 80)}`);
    }
  }

  console.log(`\n✅ Seed materiais: ${criados} criados, ${erros} erros/duplicados.`);
}

main()
  .catch((e) => {
    console.error('Erro:', e);
    process.exit(1);
  })
  .finally(() => p.$disconnect());
