export enum UserRole {
  ADMIN = 'ADMIN',
  DIRETOR_COMERCIAL = 'DIRETOR_COMERCIAL',
  GERENTE_COMERCIAL = 'GERENTE_COMERCIAL',
  EXECUTIVO_CONTAS = 'EXECUTIVO_CONTAS',
  SDR = 'SDR',
  POS_VENDAS = 'POS_VENDAS',
}
